config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users
      resources :academic_ranks
      resources :education_levels
      resources :departments
      resources :faculties
      resources :documents
      resources :research_centers
      resources :themes
      resources :research_types
      resources :calls
      resources :proposals, only: %i[index destroy]
      resources :subscribers, except: %i[destroy]
      resources :system_modules, except: %i[new destroy]
      resources :global_settings, only: %i[index edit update]

      mount Sidekiq::Web => "/sidekiq"

      root "users#index"
    end
  end

  devise_for :users
  resources :calls, only: %i[index show]
  resources :documents, only: %i[index]
  resources :profiles
  resources :research_types
  resources :themes, only: %i[index show]
  resources :research_centers

  resources :proposals do
    get "/members", to: "members#create", as: "members"
    get "/members/:id", to: "members#accept_envitation", as: "accept_envitation"
    delete "/members/:id", to: "members#decline_envitation", as: "decline_envitation"
  end

  get "/my_profile", to: "users#my_profile", as: "user_profile"
  get "/search/researcher", to: "proposals#search_researchers", as: "search_researchers"
  match "subscribers/verifyemail/:subscription_hash" => "subscribers#verify_email", :as => "verify_email", :via => :all
  get "subscribers/email_verified", to: "subscribers#email_verified", as: "email_verified"

  devise_scope :user do
    unauthenticated :user do
      root to: "devise/sessions#new"
    end

    authenticated :user do
      root "dashboard#index", as: :user_root
    end
  end
end

app/controllers/admin/research_types_controller.rb
# frozen_string_literal: true

module Admin
  class ResearchTypesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/research_types_controller.rb
# frozen_string_literal: true

class ResearchTypesController < ApplicationController
  load_and_authorize_resource
  before_action :set_research_type, only: %i[show]

  # GET /research_types or /research_types.json
  def index
    @research_types = ResearchType.all.order(:created_at).page params[:page]
  end

  # GET /research_types/1 or /research_types/1.json
  def show
  end

  # GET /research_types/1/edit
  def edit
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_research_type
    @research_type = ResearchType.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def research_type_params
    params.require(:research_type).permit(:name, :call_based, :max_budget, :gender, :fund_soure, :min_researcher,
      :max_duration, :possible_extension)
  end
end

app/views/research_types/_research_type.html.erb
<div class="mt-6 overflow-hidden bg-white shadow w-full" id="<%= dom_id research_type %>">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg font-medium leading-6 text-gray-900">Research Type Information</h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500"><%= research_type.name %> details.</p>
  </div>
  <div class="border-t border-gray-200">
    <dl>

      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Name</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= research_type.name %></dd>
      </div>

      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Call based</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= research_type.call_based %></dd>
      </div>

      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Maximum budget</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= "#{research_type.max_budget} ETB" %></dd>
      </div>

      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Allowed gender</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= research_type.gender %></dd>
      </div>

      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Fund source</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= research_type.fund_source %></dd>
      </div>

      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Minimum allowed number of researchers</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= research_type.min_researcher %></dd>
      </div>

      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Maximum duration</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= "#{research_type.max_duration} years" %></dd>
      </div>

      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Possible extention duration</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= "#{research_type.possible_extension} years" %></dd>
      </div>

    </dl>

    <% if action_name != "show" %>
      <%= link_to "Show this research type", research_type, class: "rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>
      <%= link_to "Edit this research type", edit_research_type_path(research_type), class: "rounded-lg py-3 ml-2 px-5 bg-gray-200 inline-block font-medium" %>
      <hr class="mt-6">
    <% end %>

  </div>
</div>

app/views/research_types/index.html.erb
<%= render HeaderSectionComponent.new %>

<div class="w-full overflow-hidden rounded-lg shadow-xs">
  <div class="w-full overflow-x-auto">
    <table class="w-full whitespace-no-wrap">
      <thead>
        <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b bg-gray-50">
          <th class="px-4 py-3">#</th>
          <th class="px-4 py-3">Research type</th>
          <th class="px-4 py-3">Date</th>
          <th class="px-4 py-3">Actions</th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y">
        <% @research_types.each_with_index do |research_type, index| %>
          <tr class="text-gray-700">
            <td class="px-4 py-3 text-sm">
              <%= index + 1 %>
            </td>
            <td class="px-4 py-3 text-sm">
              <%= link_to research_type.name, research_type_path(research_type) %>
            </td>
            <td class="px-4 py-3 text-sm">
              <%= research_type.created_at %>
            </td>
            <td class="px-4 py-3">
              <div class="flex items-center space-x-4 text-sm">
                <%= link_to research_type_path(research_type), class: "flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg focus:outline-none focus:shadow-outline-gray" do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %>
              </div>
            </td>
          </tr>

        <% end %>
      </tbody>
    </table>
  </div>

  <%= paginate @research_types %>
</div>

app/views/research_types/show.html.erb
<div class="w-full flex">
  <div class="w-full mx-auto">

    <%= render @research_type %>

    <%= link_to "Edit this research_type", edit_research_type_path(@research_type), class: "mt-2 py-3 px-5 bg-gray-200 text-sm inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this research_type", research_type_path(@research_type), method: :delete, class: "mt-2 py-3 px-5 bg-gray-200 text-sm font-medium" %>
    </div>
    <%= link_to "Back to research_types", research_types_path, class: "ml-2 py-3 px-5 bg-gray-200 text-sm inline-block font-medium" %>
  </div>
</div>