config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users
      resources :academic_ranks
      resources :education_levels
      resources :departments
      resources :faculties
      resources :documents
      resources :research_centers
      resources :themes
      resources :research_types
      resources :calls
      resources :proposals, only: %i[index destroy]
      resources :subscribers, except: %i[destroy]
      resources :system_modules, except: %i[new destroy]
      resources :global_settings, only: %i[index edit update]

      mount Sidekiq::Web => "/sidekiq"

      root "users#index"
    end
  end

  devise_for :users
  resources :calls, only: %i[index show]
  resources :documents, only: %i[index]
  resources :profiles
  resources :research_types
  resources :themes, only: %i[index show]
  resources :research_centers

  resources :proposals do
    get "/members", to: "members#create", as: "members"
    get "/members/:id", to: "members#accept_envitation", as: "accept_envitation"
    delete "/members/:id", to: "members#decline_envitation", as: "decline_envitation"
  end

  get "/my_profile", to: "users#my_profile", as: "user_profile"
  get "/search/researcher", to: "proposals#search_researchers", as: "search_researchers"
  match "subscribers/verifyemail/:subscription_hash" => "subscribers#verify_email", :as => "verify_email", :via => :all
  get "subscribers/email_verified", to: "subscribers#email_verified", as: "email_verified"

  devise_scope :user do
    unauthenticated :user do
      root to: "devise/sessions#new"
    end

    authenticated :user do
      root "dashboard#index", as: :user_root
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase) %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_mailer_footer.html.erb
<div class="footer">
  <table role="presentation" cellpadding="0" cellspacing="0">
    <tr>
      <td class="content-block">
        <span class="apple-link">Arba Minch University, P.O. Box 21, Tel: +251-46881-4986</span>
        <% if subscribed %>
          <br> Don't like these emails? <a href="http://i.imgur.com/CScmqnj.gif"><b>Unsubscribe</b></a>.
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="content-block powered-by">
        &#169; <%= Date.today.year %> All Rights Reserved.
      </td>
    </tr>
  </table>
</div>

app/views/shared/_public_header.html.erb
<div class="relative bg-gray">
  <div class="mx-auto w-full px-6 sm:px-20 shadow-lg bg-black">
    <div class="flex items-center justify-between py-5 md:justify-start md:space-x-10">
      <div class="flex justify-start lg:w-0 lg:flex-1">
        <%= link_to "RMIS", root_path, class: "self-center text-xl font-semibold whitespace-nowrap text-white" %>
      </div>
      <div class="-my-2 -mr-2 md:hidden">
        <button type="button" class="inline-flex items-center justify-center rounded-md bg-white p-2 text-bodydark1 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-purple-500" aria-expanded="false">
          <span class="sr-only">Open menu</span>
          <!-- Heroicon name: outline/bars-3 -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
      <nav class="hidden space-x-10 md:flex">

        <a href="#" class="text-base font-medium text-bodydark1 hover:text-white">About</a>
        <%= link_to "Documents", documents_path, class: "text-base font-medium text-bodydark1 hover:text-white" %>
        <a href="#" class="text-base font-medium text-bodydark1 hover:text-white">Help</a>

      </nav>
      <div class="hidden items-center justify-end md:flex md:flex-1 lg:w-0 space-x-10">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <%= link_to "Admin", admin_root_path, method: :delete, class: "whitespace-nowrap text-base font-medium text-gray-500 hover:text-white" %>
          <% end %>
          <%= button_to "Signout", destroy_user_session_path, method: :delete, class: "whitespace-nowrap text-base font-medium text-bodydark1 hover:text-white" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "whitespace-nowrap text-base font-medium text-bodydark1 hover:text-white" %>
          <%= link_to "Sign up", new_user_registration_path, class: "ml-8 inline-flex items-center justify-center whitespace-nowrap rounded-md border border-transparent bg-primary px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-purple-700" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/shared/_sidebar.html.erb
<aside
  :class="sidebarToggle ? 'translate-x-0' : '-translate-x-full'"
  class="absolute left-0 top-0 z-9999 flex h-screen w-72.5 flex-col overflow-y-hidden bg-black duration-300 ease-linear dark:bg-boxdark lg:static lg:translate-x-0"
  @click.outside="sidebarToggle = false"
>
  <!-- SIDEBAR HEADER -->
  <div class="flex items-center justify-between gap-2 px-6 py-5.5 lg:py-6.5">
    <%= link_to "RMIS", root_path, class: "lg:justify-self-center text-white text-2xl outline outline-1 hover:outline-2 px-2 py-1 dark:text-purple-800" %>

    <button
      class="block lg:hidden"
      @click.stop="sidebarToggle = !sidebarToggle"
    >
      <%= icon "arrow-left", width: "25", height: "23", class: "block lg:hidden" %>
    </button>
  </div>
  <!-- SIDEBAR HEADER -->

  <div
    class="no-scrollbar flex flex-col overflow-y-auto duration-300 ease-linear"
  >
    <!-- Sidebar Menu -->
    <nav
      class="mt-2 py-4 px-4 lg:mt-9 lg:px-6"
      x-data="{selected: $persist('Dashboard')}"
    >
      <!-- Menu Group -->
      <div>
        <%= menu_title "menu" %>

        <ul class="mb-6 flex flex-col gap-1.5">

          <%= render SidebarMenuItemComponent.new "Dashboard", to: user_root_path, icon_name: 'grid-alt' %>
          <%= render SidebarMenuItemComponent.new "Calendar", to: "#", icon_name: 'calendar', active: current_page?("#") %>
          <%= render SidebarMenuItemComponent.new "Proposals", to: proposals_path, icon_name: 'pencil-alt' %>
          <%= render SidebarMenuItemComponent.new "Documents", to: documents_path, icon_name: 'files', auth_check: SystemModule.enabled?(:document_management) %>
          <%= render SidebarMenuItemComponent.new "Research Calls", to: calls_path, icon_name: 'bullhorn', auth_check: SystemModule.enabled?(:call_management) %>
        </ul>
      </div>

    </nav>
    <!-- Sidebar Menu -->

  </div>
</aside>