config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users
      resources :academic_ranks
      resources :education_levels
      resources :departments
      resources :faculties
      resources :documents
      resources :research_centers
      resources :themes
      resources :research_types
      resources :calls
      resources :proposals, only: %i[index destroy]
      resources :subscribers, except: %i[destroy]
      resources :system_modules, except: %i[new destroy]
      resources :global_settings, only: %i[index edit update]

      mount Sidekiq::Web => "/sidekiq"

      root "users#index"
    end
  end

  devise_for :users
  resources :calls, only: %i[index show]
  resources :documents, only: %i[index]
  resources :profiles
  resources :research_types
  resources :themes, only: %i[index show]
  resources :research_centers

  resources :proposals do
    get "/members", to: "members#create", as: "members"
    get "/members/:id", to: "members#accept_envitation", as: "accept_envitation"
    delete "/members/:id", to: "members#decline_envitation", as: "decline_envitation"
  end

  get "/my_profile", to: "users#my_profile", as: "user_profile"
  get "/search/researcher", to: "proposals#search_researchers", as: "search_researchers"
  match "subscribers/verifyemail/:subscription_hash" => "subscribers#verify_email", :as => "verify_email", :via => :all
  get "subscribers/email_verified", to: "subscribers#email_verified", as: "email_verified"

  devise_scope :user do
    unauthenticated :user do
      root to: "devise/sessions#new"
    end

    authenticated :user do
      root "dashboard#index", as: :user_root
    end
  end
end

app/models/proposal.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: proposals
#
#  id               :bigint           not null, primary key
#  abstract         :text
#  attachement      :string
#  budget           :integer
#  code             :string
#  status           :integer          default("initialized")
#  title            :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  call_id          :bigint
#  research_type_id :bigint           not null
#  theme_id         :bigint           not null
#  user_id          :bigint           not null
#
# Indexes
#
#  index_proposals_on_call_id           (call_id)
#  index_proposals_on_code              (code) UNIQUE
#  index_proposals_on_research_type_id  (research_type_id)
#  index_proposals_on_theme_id          (theme_id)
#  index_proposals_on_user_id           (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (call_id => calls.id)
#  fk_rails_...  (research_type_id => research_types.id)
#  fk_rails_...  (theme_id => themes.id)
#  fk_rails_...  (user_id => users.id)
#
class Proposal < ApplicationRecord
  after_create :add_pi, :add_code
  belongs_to :user
  belongs_to :call, optional: true
  belongs_to :research_type
  belongs_to :theme

  enum :status, {initialized: 0, submitted: 1, accepted: 2}

  validates :attachement, :title, :budget, presence: true

  has_many :members, dependent: :destroy
  has_many :users, through: :members

  scope :joined, lambda { |user|
                   joins(:members).where("members.user_id = ?", user.id).where("members.status = ?", Member.statuses[:joined])
                 }

  private

  def add_pi
    members.create(user:, proposal: self, role: Member.roles[:principal_investigator],
      status: Member.statuses[:joined])
  end

  def add_code
    self.code = "RMIS-#{id}/#{Date.current.year}"
  end
end

app/controllers/admin/proposals_controller.rb
# frozen_string_literal: true

module Admin
  class ProposalsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/proposals_controller.rb
# frozen_string_literal: true

class ProposalsController < ApplicationController
  load_and_authorize_resource

  before_action :set_breadcrumbs

  def index
    @proposals = Proposal.joined(current_user).page params[:page]
    @envitations = Member.envitations(current_user)
  end

  def new
    @proposal = Proposal.new
    @research_types = ResearchType.all
  end

  def create
    @proposal = Proposal.new(proposal_params)
    @proposal.user_id = current_user.id

    if @proposal.save
      redirect_to proposals_path, notice: "Successfully added."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy

    respond_to do |format|
      format.html { redirect_to proposals_url, notice: "Proposal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def show
    @proposal = Proposal.find(params["id"])
    @members = Member.where(proposal_id: params["id"])
      .includes(:user)
      .page(params[:page])
      .per(params[:per])
      .max_paginates_per(4)
    @researchers = User.not_members_of(@proposal).page(params[:page]).per(params[:per]).max_paginates_per(4)
  end

  def search_researchers
    @proposal = Proposal.find_by_id(params["proposal_id"])

    if turbo_frame_request?
      @researchers = if params["search_key"].present?
        User.not_members_of(@proposal).search_by_name(params["search_key"]).page(params[:page]).max_paginates_per(4)
      else
        User.not_members_of(@proposal).page(params[:page]).max_paginates_per(4)
      end
    end
    render partial: "researchers", locals: {researchers: @researchers, proposal: @proposal}
  end

  private

  def proposal_params
    params.require(:proposal).permit(:id, :title, :attachement, :abstract, :call_id, :theme_id, :research_type_id,
      :budget)
  end

  def search_params
    params.permit(:search_key, :proposal_id)
  end

  def set_breadcrumbs
    add_breadcrumb "Dashboard", root_path
    add_breadcrumb "Proposals", proposals_path
  end
end

app/helpers/proposals_helper.rb
# frozen_string_literal: true

module ProposalsHelper
  def status_for(proposal)
    case proposal.status
    when "initialized"
      content_tag(:span, proposal.status,
        class: "px-3 mt-2 py-1 font-semibold leading-tight text-black-700 bg-green-100 rounded-full")
    when "submited"
      content_tag(:span, proposal.status,
        class: "px-3 mt-2 py-1 font-semibold leading-tight text-black-700 bg-orange-100 rounded-full")
    when "accepted"
      content_tag(:span, proposal.status,
        class: "px-3 mt-2 py-1 font-semibold leading-tight text-black-700 bg-blue-100 rounded-full")
    else
      content_tag(:span, "unkown",
        class: "px-3 mt-2 py-1 font-semibold leading-tight text-black-700 bg-orange-100 rounded-full")
    end
  end
end

app/views/proposals/_members.html.erb
<%= turbo_frame_tag "members" do %>
  <table class="w-full whitespace-no-wrap">
    <thead>
      <tr
        class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b">
        <th class="px-4 py-3">Researcher</th>
        <th class="px-4 py-3">Role</th>
        <th class="px-4 py-3">Status</th>
        <th class="px-4 py-3">Date</th>
        <th class="px-4 py-3">Actions</th>
      </tr>
    </thead>
    <tbody
      class="bg-white divide-y">
      <% members.each do |member| %>
        <tr class="text-gray-700">
          <td class="px-4 py-3">
            <div class="flex items-center text-sm">
              <!-- Avatar with inset shadow -->
              <%= avatar_for member.user, size: 8, div_class: "mr-3" %>

              <div>
                <p class="font-semibold"><%= member.user.full_name %></p>
                <p class="text-xs text-gray-600">
                  <%= member.user.email %>
                </p>
              </div>
            </div>

          </td>
          <td class="px-4 py-3 text-xs">
            <%= content_tag(:span, member.role, class: "px-2 py-1 font-semibold leading-tight text-gray-700 bg-gray-100 rounded-full") %>
          </td>

          <td class="px-4 py-3 text-xs">
            <%= member_status_for member %>
          </td>

          <td class="px-4 py-3 text-sm">
            <%= member.created_at.to_date %>
          </td>

          <td class="px-4 py-3">
            <div class="flex items-center space-x-4 text-sm">
              <%= link_to icon("fas", "edit 2x"), proposal_path(member.id), html: {class: "flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg focus:outline-none focus:shadow-outline-gray"} %>
              <%= button_to icon("fas", "trash 2x"), proposal_path(member.id), method: :destroy, html: {class: "flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg focus:outline-none focus:shadow-outline-gray"} %>
            </div>
          </td>
        </tr>

      <% end %>

    </tbody>
  </table>

  <%= paginate members %>
<% end %>

app/views/proposals/_researchers.html.erb
<%= turbo_frame_tag "researchers" do %>

  <table class="w-full whitespace-no-wrap">
    <thead>
      <tr
        class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b">
        <th class="px-4 py-2">Researcher</th>
        <th class="px-4 py-2  grid justify-items-end">Actions</th>
      </tr>
    </thead>
    <tbody
      class="bg-white divide-y">
      <% researchers.each do |researcher| %>
        <tr class="text-gray-700">
          <td class="px-4 py-2">
            <%= link_to user_path(researcher), data: {turbo_frame: "user_modal"}, class: "flex items-center text-sm"  do %>
              <!-- Avatar with inset shadow -->
              <%= avatar_for researcher, size: 8, div_class: "mr-3" %>
              <div>
                <p class="font-semibold"><%= researcher.full_name %></p>
                <p class="text-xs text-gray-600">
                  <%= researcher.email %>
                </p>
              </div>
            <% end %>

          </td>

          <td class="px-4 py-2 grid justify-items-end">
            <div class="space-x-4 text-sm flex align-center">
              <%= link_to "Envite", proposal_members_path(@proposal, user_id: researcher.id), data: {turbo_frame: "_top"}, class: "bg-blue-500 hover:bg-blue-400 text-white font-bold pt-2 pb-1 px-4 border-b-4 border-blue-700 hover:border-blue-500" %>
            </div>
          </td>
        </tr>

      <% end %>

    </tbody>
  </table>

  <%= paginate researchers %>
<% end %>

app/views/proposals/index.html.erb
<div class="w-full overflow-hidden rounded-lg shadow-sm">
  <div class="w-full overflow-x-auto">
    <%= render HeaderSectionComponent.new(title: "My proposals") %>
    <table class="w-full whitespace-no-wrap">
      <thead>
        <tr
          class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b bg-gray-50">
          <th class="px-4 py-3">Title</th>
          <th class="px-4 py-3">Status</th>
          <th class="px-4 py-3">Proposal</th>
          <th class="px-4 py-3">Date</th>
          <th class="px-4 py-3">Actions</th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y">
        <% if @proposals.present? %>
          <% @proposals.each do |proposal| %>
            <tr class="text-gray-700">
              <td class="px-4 py-3 text-sm">
                <%= link_to proposal.title, proposal_path(proposal.id), class: "text-blue-700 font-medium hover:text-blue-800" %>
              </td>
              <td class="px-4 py-3 text-xs">
                <%= status_for proposal %>
              </td>
              <td>
                <%= link_to proposal.attachement_url, target: "_blank", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-3 rounded-full inline-flex items-center" do %>
                  <svg class="fill-current w-3 h-3 mr-2 text-sm" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z" /></svg>
                  <span class="text-sm">Download</span>
                <% end %>
              </td>
              <td class="px-4 py-3 text-sm">
                <%= proposal.created_at.to_date %>
              </td>
              <td class="px-4 py-3">
                <div class="flex items-center space-x-4 text-sm">
                  <%= link_to icon("fas", "edit 2x"), proposal_path(proposal.id), class: "py-2 text-sm text-purple-600 rounded-lg focus:outline-none focus:shadow-outline-gray" %>
                  <%= button_to icon("fas", "trash 2x"), proposal_path(proposal.id), method: :destroy, class: "py-2 text-sm text-red-600 rounded-lg focus:outline-none focus:shadow-outline-gray" %>
                </div>
              </td>
            </tr>

          <% end %>
        <% else %>
          <tr class="text-gray-700">
            <td class="px-4 py-3 text-center" colspan="5">No proposal found</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= paginate @proposals %>
</div>

<% if @envitations.present? %>
  <div class="bg-white mt-6 p-4 border-t border-l border-r rounded-5 shadow-sm">
    <h2 class="my-5 text-2xl font-semibold text-gray-700">Envitations</h2>

    <div class="w-full overflow-hidden rounded-lg shadow-xs">
      <div class="w-full overflow-x-auto">
        <table class="w-full whitespace-no-wrap">
          <thead>
            <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b">
              <th class="px-4 py-3">Title</th>
              <th class="px-4 py-3">My Status</th>
              <th class="px-4 py-3">Proposal</th>
              <th class="px-4 py-3">Date</th>
              <th class="px-4 py-3">Actions</th>
            </tr>
          </thead>
          <tbody
            class="bg-white divide-y">
            <% @envitations.each do |envitation| %>
              <tr class="text-gray-700">
                <td class="px-4 py-3 text-sm">
                  <%= link_to proposal_path(envitation.proposal.id) do %>
                    <p class="font-semibold text-blue-700 font-medium hover:text-blue-800"><%= envitation.proposal.title %></p>
                    <p class="text-xs text-gray-600 mt-2">
                      <%= status_for envitation.proposal %>
                    </p>

                  <% end %>
                </td>
                <td class="px-4 py-3 text-xs">
                  <%= content_tag(:span, envitation.status, class: "px-2 py-1 font-semibold leading-tight text-orange-700 bg-orange-100 rounded-full") %>
                </td>
                <td>
                  <%= link_to envitation.proposal.attachement_url, target: "_blank", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-3 rounded-full inline-flex items-center" do %>
                    <svg class="fill-current w-3 h-3 mr-2 text-sm" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z" /></svg>
                    <span class="text-sm">Download</span>
                  <% end %>
                </td>
                <td class="px-4 py-3 text-sm">
                  <%= envitation.proposal.created_at.to_date %>
                </td>
                <td class="px-4 py-3">
                  <div class="flex items-center space-x-2 text-sm">
                    <%= link_to "Accept", proposal_accept_envitation_path(envitation.proposal, envitation), class: "bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 hover:border-blue-500 rounded-full" %>
                    <%= link_to "Decline", proposal_decline_envitation_path(envitation.proposal, envitation), class: "bg-orange-500 hover:bg-orange-400 text-white font-bold py-2 px-4 hover:border-orange-500 rounded-full" %>
                  </div>
                </td>
              </tr>

            <% end %>

          </tbody>
        </table>
      </div>

      <%= paginate @proposals %>
    </div>
  </div>
<% end %>

app/views/proposals/modal.html.erb
<!-- Modal backdrop. This what you want to place close to the closing body tag -->
    <div
      x-transition:enter="transition ease-out duration-150"
      x-transition:enter-start="opacity-0"
      x-transition:enter-end="opacity-100"
      x-transition:leave="transition ease-in duration-150"
      x-transition:leave-start="opacity-100"
      x-transition:leave-end="opacity-0"
      class="fixed inset-0 z-30 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center">
      <!-- Modal -->
      <div
        x-transition:enter="transition ease-out duration-150"
        x-transition:enter-start="opacity-0 transform translate-y-1/2"
        x-transition:enter-end="opacity-100"
        x-transition:leave="transition ease-in duration-150"
        x-transition:leave-start="opacity-100"
        x-transition:leave-end="opacity-0  transform translate-y-1/2"
        class="w-full px-6 py-4 overflow-hidden bg-white rounded-t-lg dark:bg-gray-800 sm:rounded-lg sm:m-4 sm:max-w-xl"
        role="dialog"
        id="modal">
        <!-- Remove header if you don't want a close icon. Use modal body to place modal tile. -->
        <header class="flex justify-end">
          <button
            class="inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-gray-200 hover: hover:text-gray-700"
            aria-label="close"
            click="closeModal">
            <svg
              class="w-4 h-4"
              fill="currentColor"
              viewBox="0 0 20 20"
              role="img"
              aria-hidden="true">
              <path
                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                clip-rule="evenodd"
                fill-rule="evenodd"></path>
            </svg>
          </button>
        </header>
        <!-- Modal body -->
        <div class="mt-4 mb-6">
          <!-- Modal title -->
          <p
            class="mb-2 text-lg font-semibold text-gray-700 dark:text-gray-300">
            Modal header
          </p>
          <!-- Modal description -->
          <p class="text-sm text-gray-700 dark:text-gray-400">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nostrum et
            eligendi repudiandae voluptatem tempore!
          </p>
        </div>
        <footer
          class="flex flex-col items-center justify-end px-6 py-3 -mx-6 -mb-4 space-y-4 sm:space-y-0 sm:space-x-6 sm:flex-row bg-gray-50 dark:bg-gray-800">
          <button
            click="closeModal"
            class="w-full px-5 py-3 text-sm font-medium leading-5 text-white text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 sm:px-4 sm:py-2 sm:w-auto active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray">
            Cancel
          </button>
          <button
            class="w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
            Accept
          </button>
        </footer>
      </div>
    </div>
    <!-- End of modal backdrop -->

app/views/proposals/new.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700">Create Proposal</h2>

<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md visible">
  <%= simple_form_for @proposal, url: {action: "create"}, data: {controller: "new-proposal", "new-proposal-types-value": @research_types.to_json.to_s}, method: :post, local: true, html: {multipart: true} do |f| %>

    <%= render "shared/error_messages", resource: @proposal %>

    <%= f.error_notification %>

    <%= f.input :title, input_html: {class: "proposal-input"} %>
    <%= f.association :research_type, input_html: {data: {action: "new-proposal#makeChanges"}}, default: 0 %>
    <%= f.association :call, wrapper_html: {data: {"new-proposal-target": "callWrapper"}, class: "hidden"}, input_html: {data: {"new-proposal-target": "callInput"}, class: "proposal-input"} %>
    <%= f.association :theme, input_html: {class: "proposal-input"} %>
    <%= f.input :attachement, label: "Proposal", input_html: {class: "proposal-input"} %>
    <%= f.input :abstract, input_html: {class: "proposal-input"} %>
    <%= f.input :budget, input_html: {data: {"new-proposal-target": "budgetInput"}, class: "proposal-input", min: "0"} %>

    <label class="block mt-4 text-sm">
      <%= f.button :submit, "Add proposal", class: "proposal-input" %>
    </label>

  <% end %>
</div>

app/views/proposals/show.html.erb
<h2
  class="my-6 text-2xl font-semibold text-gray-700">
  Proposal
</h2>

<div class="w-full overflow-hidden rounded-lg shadow-xs">

  <div class="w-full px-4 py-3 mb-8 bg-white rounded-lg shadow-md">

    <h4 class="mb-4 font-semibold text-gray-600"><%= @proposal.title %></h4>

    <details>
      <summary class="text-gray-600 cursor-pointer">Abstract</summary>
      <div>
        <p class="mb-4 text-gray-600">
          <%= @proposal.abstract %></p>
      </div>
    </details>

    <div class="w-full pt-8 flex justify-end">
      <%= link_to @proposal.attachement_url, class: "rounded-full flex items-center justify-between px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-blue-600 border border-transparent active:bg-blue-600 hover:bg-blue-700 focus:outline-none focus:shadow-outline-blue" do %>
        <%= icon "fas", "download" %>
        <%= content_tag(:span, "Download", class: "ml-2") %>
      <% end %>
    </div>
  </div>

  <% if @proposal.user == current_user %>
    <h4 class="mb-4 text-lg font-semibold text-gray-600">Envite Researchers to the Proposal</h4>

    <div class="px-4 py-3 mb-8 bg-white rounded-lg  overflow-x-auto shadow-md">
      <%= form_with(url: search_researchers_path, method: :get, data: {turbo_frame: "researchers"}, html: {autocomplete: "off"}) do |f| %>
        <%= f.hidden_field :proposal_id, value: @proposal.id %>
        <div class="relative text-gray-500 focus-within:text-purple-600 mb-6">
          <%= f.search_field :search_key, class: "block w-full pr-20 mt-1 text-sm text-black focus:border-purple-400 focus:outline-none focus:shadow-outline-purple form-input  rounded-3xl", placeholder: "Search researcher ...", min: "2" %>
          <%= f.submit "Search", class: "cursor-pointer absolute inset-y-0 right-0 px-4 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple rounded-r-3xl" %>
        </div>

      <% end %>

      <%= render "researchers", researchers: @researchers %>

    </div>
  <% end %>

  <h4 class="mb-4 text-lg font-semibold text-gray-600">Members</h4>

  <div class="px-4 py-3 mb-8 bg-white rounded-lg  overflow-x-auto shadow-md">
    <%= render "members", members: @members %>
  </div>

</div>